### PR TITLE
Update version number to 1.1.0

### PR DESCRIPTION
**Pull request by yongja79**
* Update the version number to 1.1.0 in the main branch
Signed-off-by: Jason Yong <jason_yong@uk.ibm.com>

### CODE REVIEW

**Review by leochr — COMMENTED** [review]
@yongja79 Thanks for the PR. To support upgrade, `olm.skipRange: '>=1.0.0 <1.1.0'` should be added to ClusterServiceVersion at `metadata.annotations`

**Comment by yongja79** [comment]
@leochr `olm.skipRange` added as well as `replaces` as I think that is also required

**Comment by leochr** [comment]
@yongja79 Thanks for the update. Only skipRange is required. `replaces` is not needed for minor version updates since it should be included in a new channel. Please update references to `v1.0` channel in these files to `v1.1`

- bundle.Dockerfile
- Makefile
- scripts/dev.sh (this should not be hardcoded, I'll open a separate issue)

and then run `make bundle` to update the bundle artifacts.

**Comment by leochr** [comment]
Included via another PR. Closing.

**Pull request closed without merging**
