### PR TITLE
add env_id to archive pipeline

### PR DESCRIPTION
**Pull request by leochr**
Add change from https://github.com/WASdev/websphere-liberty-operator/pull/512/files to `.one-pipeline-archive.yaml`

### CODE REVIEW

**Comment by leochr** [comment]
@mcurran-us seems like the change to add env_id is also required to archive pipeline (which backs up WLO source code periodically). I am not entirely sure whether [this instance of the same URL](https://github.com/WASdev/websphere-liberty-operator/blob/c4c61f515d13c4e11f7e61744396ab90adb66687/scripts/pipeline/getCluster.sh#L76) also needs env_id - since it's just used as reason/reference, thoughts? 
Thank you

**Comment by mcurran-us** [comment]
@leochr I looked at that previously and although I don't know for sure, it didn't look like it was intended to be used for someone to click on and get to the pipeline run.  In which case, it should be fine to leave it as. is.

**Review by mcurran-us — APPROVED** [review]
Looks good.

**Comment by leochr** [comment]
> @leochr I looked at that previously and although I don't know for sure, it didn't look like it was intended to be used for someone to click on and get to the pipeline run. In which case, it should be fine to leave it as. is.

sounds good. Thanks

**Pull request merged**
